// <auto-generated />
using Generio.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Generio.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(GenerioDbContext))]
    [Migration("20260714095200_Phase8MediaSeo")]
    partial class Phase8MediaSeo
    {
    }
}
